// Parity tests for the client-side .apkg parser. The fixtures and goldens under
// fixtures/anki/ are generated by the Go parser (backend/internal/anki/fixtures_test.go);
// this suite holds the TypeScript parser to byte-identical output, which is what lets the
// import pipeline move between server and browser without the rest of the app noticing.

import { beforeAll, describe, expect, it } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
import initSqlJs, { type SqlJsStatic } from "sql.js";
import { parseApkgBlob } from "../utils/apkg/parse";
import { parseMediaEntriesProto } from "../utils/apkg/proto";
import { maybeDecompressZstd, mimeTypeFor, parseMediaManifest } from "../utils/apkg/media";
import type { ApkgImportResult } from "../utils/apkg/types";

const nodeRequire = createRequire(import.meta.url);
const fixturesDir = path.resolve(__dirname, "..", "..", "fixtures", "anki");

let SQL: SqlJsStatic;
beforeAll(async () => {
  // Loading the wasm binary directly bypasses emscripten's environment sniffing, which gets
  // confused by happy-dom (a DOM present but no real fetch for file paths).
  const wasmBinary = fs.readFileSync(nodeRequire.resolve("sql.js/dist/sql-wasm.wasm"));
  SQL = await initSqlJs({ wasmBinary });
});

/** normalize zeroes the per-run values exactly like the Go test's normalizeResult. */
function normalize(result: ApkgImportResult): unknown {
  const clone = JSON.parse(JSON.stringify(result));
  clone.importId = "IMPORT_ID";
  clone.collection.id = "collection-IMPORT_ID";
  clone.collection.createdAt = 0;
  return clone;
}

describe("apkg parser parity with Go goldens", () => {
  for (const name of ["tiny-legacy", "tiny-modern"]) {
    it(`parses ${name}.apkg identically to the Go parser`, async () => {
      const apkg = fs.readFileSync(path.join(fixturesDir, `${name}.apkg`));
      const golden = JSON.parse(fs.readFileSync(path.join(fixturesDir, `${name}.golden.json`), "utf8"));

      const seenBlobs: Array<{ hash: string; bytes: number }> = [];
      const result = await parseApkgBlob(new Blob([apkg]), SQL, {
        onMediaBlob: (ref, bytes) => {
          seenBlobs.push({ hash: ref.hash, bytes: bytes.length });
        },
      });

      expect(normalize(result)).toEqual(golden);

      // Every manifest entry must have streamed exactly one decoded blob whose size matches.
      expect(seenBlobs).toEqual(
        (result.mediaManifest ?? []).map((m) => ({ hash: m.hash, bytes: m.bytes }))
      );
    });
  }

  it("parses the large local sample decks when present (skipped in CI)", async () => {
    const sample = path.resolve(fixturesDir, "..", "..", "RRTK_Recognition_Remembering_The_Kanji.apkg");
    if (!fs.existsSync(sample)) return; // sample decks are not committed
    const apkg = fs.readFileSync(sample);
    const result = await parseApkgBlob(new Blob([apkg]), SQL, {});
    expect(result.collection.notes.length).toBeGreaterThan(0);
    expect(result.collection.cards.length).toBeGreaterThan(0);
  }, 120_000);
});

describe("media manifest decoding", () => {
  it("decodes the legacy JSON manifest", () => {
    const raw = new TextEncoder().encode('{"0":"hello.mp3","1":"world.png"}');
    expect(parseMediaManifest(raw, false)).toEqual([
      { entryName: "0", fileName: "hello.mp3" },
      { entryName: "1", fileName: "world.png" },
    ]);
  });

  it("decodes a protobuf manifest with unknown fields skipped", () => {
    // MediaEntries { entries: [{name: "a.mp3", size: 5, sha1: <4 bytes>}] } — size and sha1
    // must be skipped, not tripped over.
    const inner = new Uint8Array([
      0x0a, 0x05, 0x61, 0x2e, 0x6d, 0x70, 0x33, // name = "a.mp3"
      0x10, 0x05, // size = 5
      0x1a, 0x04, 0xde, 0xad, 0xbe, 0xef, // sha1 = 4 bytes
    ]);
    const msg = new Uint8Array([0x0a, inner.length, ...inner]);
    expect(parseMediaEntriesProto(msg)).toEqual(["a.mp3"]);
  });

  it("throws on malformed protobuf", () => {
    expect(() => parseMediaEntriesProto(new Uint8Array([0x0a, 0xff]))).toThrow();
  });

  it("passes non-zstd bytes through unchanged", () => {
    const raw = new Uint8Array([1, 2, 3, 4]);
    expect(maybeDecompressZstd(raw)).toBe(raw);
  });

  it("maps common media extensions like the server", () => {
    expect(mimeTypeFor("audio.MP3")).toBe("audio/mpeg");
    expect(mimeTypeFor("image.png")).toBe("image/png");
    expect(mimeTypeFor("weird.xyz")).toBe("application/octet-stream");
  });
});
