import { describe, it, expect, beforeAll, vi } from "vitest";

// Isolate the unit under test from the generated data file (regenerated by
// scripts/build-kanji-insights.py) so these tests assert on the lookup/fallback
// logic itself, not on whatever kanji happen to be in the current dataset.
vi.mock("../content/n5/kanji-insights", () => ({
  KANJI_INSIGHTS: {
    "学": { keyword: "study", story: "a child under a roof studies", components: ["子", "冠"], readings: "ガク" },
    "子": { keyword: "child", story: "a child with big arms", components: [] },
    "atomic": { keyword: "atomic kanji", story: "", components: [] },
  },
  RADICAL_MEANINGS: {
    "冠": "crown radical",
  },
}));

import {
  getKanjiInsight,
  hasKanjiInsight,
  componentMeaning,
  getKanjiParts,
  isKanjiChar,
  loadExtendedKanjiInsights,
} from "../utils/kanji-insights";

describe("isKanjiChar", () => {
  it("is true for a kanji character", () => {
    expect(isKanjiChar("学")).toBe(true);
  });
  it("is false for hiragana", () => {
    expect(isKanjiChar("あ")).toBe(false);
  });
  it("is false for ascii letters and digits", () => {
    expect(isKanjiChar("A")).toBe(false);
    expect(isKanjiChar("1")).toBe(false);
  });
});

describe("getKanjiInsight / hasKanjiInsight", () => {
  it("returns the insight for a known kanji", () => {
    expect(getKanjiInsight("学")?.keyword).toBe("study");
    expect(hasKanjiInsight("学")).toBe(true);
  });

  it("returns null/false for an unknown character", () => {
    expect(getKanjiInsight("未")).toBeNull();
    expect(hasKanjiInsight("未")).toBe(false);
  });
});

describe("componentMeaning", () => {
  it("prefers a kanji's own keyword over a radical meaning", () => {
    expect(componentMeaning("子")).toBe("child");
  });

  it("falls back to RADICAL_MEANINGS when there is no kanji insight", () => {
    expect(componentMeaning("冠")).toBe("crown radical");
  });

  it("returns an empty string when nothing matches", () => {
    expect(componentMeaning("未")).toBe("");
  });
});

describe("getKanjiParts", () => {
  it("returns [] for a character with no insight", () => {
    expect(getKanjiParts("未")).toEqual([]);
  });

  it("returns [] for an atomic kanji (no components)", () => {
    expect(getKanjiParts("子")).toEqual([]);
  });

  it("maps each component to its meaning and drillable flag", () => {
    const parts = getKanjiParts("学");
    expect(parts).toEqual([
      { char: "子", meaning: "child", drillable: true },
      { char: "冠", meaning: "crown radical", drillable: false },
    ]);
  });
});

describe("loadExtendedKanjiInsights", () => {
  it("retries after a failed fetch instead of caching the rejection", async () => {
    vi.stubGlobal("fetch", vi.fn(async () => ({ ok: false, status: 500 })) as unknown as typeof fetch);
    await expect(loadExtendedKanjiInsights()).rejects.toThrow();
  });

  it("makes extended insights/radicals available as a fallback once loaded", async () => {
    vi.stubGlobal(
      "fetch",
      vi.fn(async () => ({
        ok: true,
        json: async () => ({
          insights: { "未": { keyword: "not yet", story: "a tree with a small branch", components: [] } },
          radicals: { "⺅": "person radical" },
        }),
      })) as unknown as typeof fetch
    );
    await loadExtendedKanjiInsights();

    expect(getKanjiInsight("未")?.keyword).toBe("not yet");
    expect(hasKanjiInsight("未")).toBe(true);
    expect(componentMeaning("⺅")).toBe("person radical");
  });

  it("is idempotent — a second call does not refetch", async () => {
    const fetchMock = vi.fn(async () => ({ ok: true, json: async () => ({ insights: {}, radicals: {} }) }));
    vi.stubGlobal("fetch", fetchMock as unknown as typeof fetch);
    await loadExtendedKanjiInsights();
    expect(fetchMock).not.toHaveBeenCalled();
  });
});
