// Offline vocab dictionary loader + search.
//
// Loads public/data/jmdict.json (generated by scripts/build-jmdict.py — JMdict
// common subset with Tatoeba examples) lazily on first use, builds in-memory
// search indices, and ranks results for Japanese / kana / romaji / English
// queries. The service worker caches the JSON after first fetch, so lookup
// works offline thereafter.

export interface DictSense {
  pos: string[];
  g: string[];
}

export interface DictExample {
  j: string;
  e: string;
}

export interface DictEntry {
  id: string;
  /** kanji surface forms (may be empty for kana-only words) */
  k: string[];
  /** kana readings */
  r: string[];
  s: DictSense[];
  ex?: DictExample;
}

export interface SearchResult extends DictEntry {
  score: number;
}

interface DictFile {
  version?: string;
  tags: Record<string, string>;
  words: DictEntry[];
}

let WORDS: DictEntry[] = [];
let POS_TAGS: Record<string, string> = {};
// Japanese surface/reading -> entry indices (exact match).
let jpExact = new Map<string, number[]>();
// Sorted unique Japanese keys, for prefix scanning via binary search.
let jpKeys: string[] = [];
// English gloss token -> entry indices.
let enIndex = new Map<string, number[]>();
let loadPromise: Promise<void> | null = null;

const DATA_URL = `${import.meta.env.BASE_URL}data/jmdict.json`;

function pushIndex(map: Map<string, number[]>, key: string, idx: number): void {
  const list = map.get(key);
  if (list) {
    if (list[list.length - 1] !== idx) list.push(idx);
  } else {
    map.set(key, [idx]);
  }
}

function tokenizeEnglish(text: string): string[] {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .split(/\s+/)
    .filter((t) => t.length > 1);
}

/** Lazily fetch the dictionary and build search indices. Idempotent. */
export function loadDictionary(): Promise<void> {
  if (!loadPromise) {
    loadPromise = fetch(DATA_URL)
      .then((r) => {
        if (!r.ok) throw new Error(`dictionary fetch failed: ${r.status}`);
        return r.json() as Promise<DictFile>;
      })
      .then((data) => {
        WORDS = data.words || [];
        POS_TAGS = data.tags || {};
        jpExact = new Map();
        enIndex = new Map();
        const keySet = new Set<string>();
        WORDS.forEach((w, idx) => {
          for (const form of w.k) {
            pushIndex(jpExact, form, idx);
            keySet.add(form);
          }
          for (const form of w.r) {
            pushIndex(jpExact, form, idx);
            keySet.add(form);
          }
          for (const sense of w.s) {
            for (const gloss of sense.g) {
              for (const tok of tokenizeEnglish(gloss)) pushIndex(enIndex, tok, idx);
            }
          }
        });
        jpKeys = Array.from(keySet).sort();
      })
      .catch((err) => {
        loadPromise = null; // allow retry on a later lookup
        throw err;
      });
  }
  return loadPromise;
}

export function isDictionaryLoaded(): boolean {
  return WORDS.length > 0;
}

export function posLabel(code: string): string {
  return POS_TAGS[code] || code;
}

// --- romaji -> hiragana (pragmatic Hepburn; enough for dictionary search) ---

const ROMAJI_MAP: Record<string, string> = {
  kya: "きゃ", kyu: "きゅ", kyo: "きょ", sha: "しゃ", shu: "しゅ", sho: "しょ",
  cha: "ちゃ", chu: "ちゅ", cho: "ちょ", nya: "にゃ", nyu: "にゅ", nyo: "にょ",
  hya: "ひゃ", hyu: "ひゅ", hyo: "ひょ", mya: "みゃ", myu: "みゅ", myo: "みょ",
  rya: "りゃ", ryu: "りゅ", ryo: "りょ", gya: "ぎゃ", gyu: "ぎゅ", gyo: "ぎょ",
  ja: "じゃ", ju: "じゅ", jo: "じょ", bya: "びゃ", byu: "びゅ", byo: "びょ",
  pya: "ぴゃ", pyu: "ぴゅ", pyo: "ぴょ",
  shi: "し", chi: "ち", tsu: "つ", fu: "ふ", ji: "じ",
  ka: "か", ki: "き", ku: "く", ke: "け", ko: "こ",
  sa: "さ", si: "し", su: "す", se: "せ", so: "そ",
  ta: "た", ti: "ち", tu: "つ", te: "て", to: "と",
  na: "な", ni: "に", nu: "ぬ", ne: "ね", no: "の",
  ha: "は", hi: "ひ", he: "へ", ho: "ほ",
  ma: "ま", mi: "み", mu: "む", me: "め", mo: "も",
  ya: "や", yu: "ゆ", yo: "よ",
  ra: "ら", ri: "り", ru: "る", re: "れ", ro: "ろ",
  wa: "わ", wo: "を", n: "ん",
  ga: "が", gi: "ぎ", gu: "ぐ", ge: "げ", go: "ご",
  za: "ざ", zi: "じ", zu: "ず", ze: "ぜ", zo: "ぞ",
  da: "だ", di: "ぢ", du: "づ", de: "で", do: "ど",
  ba: "ば", bi: "び", bu: "ぶ", be: "べ", bo: "ぼ",
  pa: "ぱ", pi: "ぴ", pu: "ぷ", pe: "ぺ", po: "ぽ",
  a: "あ", i: "い", u: "う", e: "え", o: "お",
};

export function romajiToHiragana(input: string): string {
  let s = input.toLowerCase().replace(/[^a-z]/g, "");
  let out = "";
  let i = 0;
  while (i < s.length) {
    // double consonant -> small tsu (e.g. "kitte" -> きって)
    if (i + 1 < s.length && s[i] === s[i + 1] && s[i] !== "n" && !"aeiou".includes(s[i])) {
      out += "っ";
      i += 1;
      continue;
    }
    let matched = false;
    for (let len = 3; len >= 1; len--) {
      const chunk = s.slice(i, i + len);
      if (ROMAJI_MAP[chunk]) {
        out += ROMAJI_MAP[chunk];
        i += len;
        matched = true;
        break;
      }
    }
    if (!matched) {
      out += s[i];
      i += 1;
    }
  }
  return out;
}

function hasJapanese(s: string): boolean {
  return /[぀-ヿ㐀-鿿豈-﫿]/.test(s);
}

// lower bound: first index in sorted jpKeys whose value >= target
function lowerBound(target: string): number {
  let lo = 0;
  let hi = jpKeys.length;
  while (lo < hi) {
    const mid = (lo + hi) >> 1;
    if (jpKeys[mid] < target) lo = mid + 1;
    else hi = mid;
  }
  return lo;
}

/**
 * Search the dictionary. Detects Japanese vs. ASCII input; ASCII queries are
 * matched both as English glosses and as romaji converted to kana. Returns up
 * to `limit` entries ranked by match quality.
 */
export function searchWords(query: string, limit = 30): SearchResult[] {
  const q = query.trim();
  if (!q || WORDS.length === 0) return [];
  const scores = new Map<number, number>();
  const bump = (idx: number, score: number) => {
    const prev = scores.get(idx);
    if (prev === undefined || score > prev) scores.set(idx, score);
  };

  const japaneseQueries = new Set<string>();
  if (hasJapanese(q)) {
    japaneseQueries.add(q);
  } else {
    const kana = romajiToHiragana(q);
    if (kana && hasJapanese(kana)) japaneseQueries.add(kana);
    // English gloss search
    const lc = q.toLowerCase();
    for (const tok of tokenizeEnglish(lc)) {
      for (const idx of enIndex.get(tok) || []) bump(idx, 300);
    }
    // gloss substring (catches multi-word / partial)
    if (lc.length >= 3) {
      WORDS.forEach((w, idx) => {
        for (const sense of w.s) {
          for (const gloss of sense.g) {
            const g = gloss.toLowerCase();
            if (g === lc) bump(idx, 600);
            else if (g.startsWith(lc)) bump(idx, 250);
            else if (g.includes(lc)) bump(idx, 120);
          }
        }
      });
    }
  }

  for (const jq of japaneseQueries) {
    // exact
    for (const idx of jpExact.get(jq) || []) bump(idx, 1000);
    // prefix scan over sorted keys
    if (jq.length >= 1) {
      for (let i = lowerBound(jq); i < jpKeys.length; i++) {
        const key = jpKeys[i];
        if (!key.startsWith(jq)) break;
        if (key === jq) continue;
        const score = 500 - Math.min(key.length - jq.length, 100);
        for (const idx of jpExact.get(key) || []) bump(idx, score);
      }
    }
  }

  const results: SearchResult[] = [];
  for (const [idx, score] of scores) {
    results.push({ ...WORDS[idx], score });
  }
  results.sort((a, b) => {
    if (b.score !== a.score) return b.score - a.score;
    // tie-break: shorter primary form first (more "core" words)
    const al = (a.k[0] || a.r[0] || "").length;
    const bl = (b.k[0] || b.r[0] || "").length;
    return al - bl;
  });
  return results.slice(0, limit);
}
