import { KANJI_INSIGHTS, RADICAL_MEANINGS, type KanjiInsight } from "../content/n5/kanji-insights";

export interface KanjiPart {
  char: string;
  meaning: string;
  drillable: boolean;
}

// The N5 course imports KANJI_INSIGHTS/RADICAL_MEANINGS synchronously and is the
// hand-audited source of truth. The dictionary-lookup feature needs decomposition
// + mnemonics for any RTK kanji, so we lazily load a superset
// (public/data/kanji-insights-full.json, generated by build-kanji-insights.py --full)
// and consult it as a fallback. Static N5 data always wins on conflict.
let extendedInsights: Record<string, KanjiInsight> = {};
let extendedRadicals: Record<string, string> = {};
let extendedPromise: Promise<void> | null = null;

const EXTENDED_URL = `${import.meta.env.BASE_URL}data/kanji-insights-full.json`;

/** Lazily fetch the full-RTK kanji superset. Idempotent; safe to call repeatedly. */
export function loadExtendedKanjiInsights(): Promise<void> {
  if (!extendedPromise) {
    extendedPromise = fetch(EXTENDED_URL)
      .then((r) => {
        if (!r.ok) throw new Error(`kanji-insights-full fetch failed: ${r.status}`);
        return r.json() as Promise<{ insights?: Record<string, KanjiInsight>; radicals?: Record<string, string> }>;
      })
      .then((data) => {
        extendedInsights = data.insights || {};
        extendedRadicals = data.radicals || {};
      })
      .catch((err) => {
        extendedPromise = null; // allow retry
        throw err;
      });
  }
  return extendedPromise;
}

export function getKanjiInsight(char: string): KanjiInsight | null {
  return KANJI_INSIGHTS[char] || extendedInsights[char] || null;
}

export function hasKanjiInsight(char: string): boolean {
  return Boolean(KANJI_INSIGHTS[char] || extendedInsights[char]);
}

export function componentMeaning(char: string): string {
  return (
    KANJI_INSIGHTS[char]?.keyword ||
    extendedInsights[char]?.keyword ||
    RADICAL_MEANINGS[char] ||
    extendedRadicals[char] ||
    ""
  );
}

export function getKanjiParts(char: string): KanjiPart[] {
  const insight = KANJI_INSIGHTS[char] || extendedInsights[char];
  if (!insight) return [];
  return insight.components.map((component) => ({
    char: component,
    meaning: componentMeaning(component),
    drillable: hasKanjiInsight(component),
  }));
}

export function isKanjiChar(char: string): boolean {
  return /\p{Script=Han}/u.test(char);
}
